services:
  server:
    build:
      context: ./Server
    container_name: grpc-server
    ports:
      - "5123:5123"
    environment:
      - ASPNETCORE_URLS=http://+:5123
    networks:
      - grpc_net

  nginx:
    image: nginx:latest
    container_name: grpc-nginx
    ports:
      - "5000:5000"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - server
    networks:
      - grpc_net

networks:
  grpc_net:
    driver: bridge
